spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_shop
    username: tech_user
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml